backend: db
tables:
   user: users
   group: associations
   role: roles
   user_group: users_associations
   user_role: users_roles
fields:
   user:
       id: id
       username: username
       password: password
       active: active 
   group:
       id: id
       name: name
       active: active
   role:
       id: id
       name: name
       active: active
   user_group:
       fk_user_id: user_id
       fk_group_id: association_id
   user_role:
       fk_user_id: user_id
       fk_role_id: role_id
use_groups: 1
use_roles: 1
use_active: 1
active_value: 1
password_encryption: true
encryption: md5
session_user: activeUser
locations:
   denied: /denied
   login: /login
   logout: /logout
   post_logout: /
denied:
    handling: inplace
    template: response/access_denied.tpl
