directories: 
    zoop: %ZOOP_DIR%/guicontrol/GuiControls/
    app: %APP_DIR%/view/GuiControls/
    
multi_value_separator: ', '

#DANGER! DON'T ENABLE THIS!
enable_show_passwords: false

# Set this value to false if you don't want 'required' stars.
required_indicator: '<span class="required">*</span>'