directories: 
    public: public
    temp: %APP_TEMP_DIR%/gui
    base: %APP_DIR%/view/templates
    template: %APP_DIR%/view/templates
    base_template: %ZOOP_DIR%/gui/templates
    compile: %APP_TEMP_DIR%/gui/compiled
    cache: %APP_TEMP_DIR%/gui/cache
    plugins:
        - %APP_DIR%/view/guiplugins
        - %ZOOP_DIR%/gui/plugins
strip_html: false
caching: 0

# optionally, do a css reset and set base styles (thanks yui!)
use_css_reset: 0
use_css_base: 0

# define page regions and default templates
regions:
    - header
    - sidebar
    - content
    - footer
primary_region: content

# default template files for various uses...
templates:
    html: base/html.tpl
    header: base/header.tpl
    sidebar: base/sidebar.tpl
    content: base/content.tpl
    footer: base/footer.tpl
    formz: forms/formz.tpl
    message: base/message.tpl
