driver: forms
type: list
lotsa_classes: true

# Disabling CSRF protection is a Bad Idea. Don't change this unless you want to get haxx0rd.
disable_csrf_protection: false

# Hide the ID column by default in Formz lists.
hide_id_field: true

# Order Formz lists by the title field (default).
sort_by_title: true

# Formz pagination defaults.
paginate:
    limit: 25
    
    # TODO: would like to enable stuff like this later. not now.
    # format: 'First Previous Next Last'
    # format: '<< < 1 2 3 4 5 > >>'
    # format: '<< < 1 2 3 4 ... 10 > >>'
    
    # disable any pagination links by setting them to 0... i.e. first: 0 will remove the first link.
    format:
        first: '<<'
        prev: '<'
        mid: [1, 2, 3, '...', 5]
        next: '>'
        last: '>>'
        
    format_delimiter: ' '

rowaction:
    # Formz threshold for combining row action columns.
    column_threshold: 3

list_actions:
    separator: ' '
    position: both

checkboxes_threshold: 15

# Priority for autoselecting table title fields within relations
title_field_priority:
    - name
    - label
    - title
    - alias
    - username
    - first_name
    - last_name
    - firstname
    - lastname
    - date
# Label for 'nothing selected' in a dropdown.
# Will autoreplace %field% with the actual field name.
select_null_value: - Select %field% -
