## Path to Doctrine.php
include_path:

## Doctrine paths
models_dir: %APP_DIR%/model/doctrine/models
migrations_dir: %APP_DIR%/model/doctrine/migrations
data_fixtures_dir: %APP_DIR%/model/doctrine/data/fixtures
sql_dir: %APP_DIR%/model/doctrine/data/sql
yaml_schema_dir: %APP_DIR%/model/doctrine/schema
listeners_dir: %APP_DIR%/model/doctrine/listeners

## Doctrine attributes
model_loading: conservative
use_dql_callbacks: 1

## Doctrine listeners
listeners:
    Doctrine_EventListener:
        - class: # class name
          level: # manager, active_connection, or an actual connection name
    Doctrine_EventListener_Interface:
        - class:
          level:
    Doctrine_Overloadable:
        - class:
          level:
    Doctrine_Record_Listener:
        - class:
          level:

## Connections
dsn:
charset:
active_connection: _dsn_connection
#connections:
#    default_connection:
#        dsn:
#        charset:
