save_in_session: false
directory: %APP_DIR%/zones
decorators_directory: %APP_DIR%/zones/decoratorZones
aliases:
    global_redirect: 0
crud_zone:
    auto_paginate: 0
    messages:
        # Delete confirmation message. Can include %id% and %title% fields.
        confirm_delete: "Are you sure you want to delete: <strong>%title%</strong>?"
allowable_output: [ xml, json, yaml, serialized, csv, xls, html, pdf, png, rss, ajax ]

zoopfile:
    # The Finfo PECL extension has some serious issues.
    # Disable if you have problems displaying files with Zoopfile.
    use_finfo_extension: 0