<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Association extends BaseAssociation
{


  public function setUp()
  {
	  
	  $this->hasMany('User', 		array('local' => 'association_id',
		  								'foreign' => 'user_id',
										'refClass' => 'UserAssociation'));
  }

}
