<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Role extends BaseRole
{


  public function setUp()
  {
	  $this->hasMany('User', array('local' => 'role_id',
		  								'foreign' =>  'user_id',
										'refClass' => 'UserRole'));
  }

}
